#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PLAYER_BASE_HP 100
#define PLAYER_BASE_MANA 50
#define PLAYER_BASE_STRENGTH 10
#define PLAYER_BASE_DEFENSE 5
#define PLAYER_BASE_MAGIC 5
#define PLAYER_BASE_EXP_TO_NEXT 100

#define PLAYER_HP_PER_LEVEL 20
#define PLAYER_STRENGTH_PER_LEVEL 2
#define PLAYER_DEFENSE_PER_LEVEL 1

#define ENEMY_BASE_HP 30
#define ENEMY_HP_PER_TYPE 20
#define ENEMY_BASE_DAMAGE 5
#define ENEMY_DAMAGE_PER_TYPE 5
#define ENEMY_BASE_EXP 10
#define ENEMY_EXP_PER_TYPE 5

#define ENEMY_GOLD_MIN 2
#define ENEMY_GOLD_MAX 8

#define PLAYER_DISTANCE_FROM_ENEMIES 3
#define MAX_SPAWN_ATTEMPTS 100
#define INITIAL_ENEMY_COUNT 5

#define MELEE_DAMAGE_VARIANCE 2
#define MIN_DAMAGE 1

#endif
