#ifndef GRAPHICS_CONSTANTS_H
#define GRAPHICS_CONSTANTS_H

#include "raylib.h"

#define TILE_FLOOR_COLOR (Color){64, 64, 64, 255}
#define TILE_WALL_COLOR (Color){32, 32, 32, 255}
#define TILE_BORDER_COLOR (Color){48, 48, 48, 255}

#define ENEMY_TYPE_0_COLOR RED
#define ENEMY_TYPE_1_COLOR PURPLE
#define ENEMY_TYPE_2_COLOR MAROON

#define ENEMY_TYPE_0_TINT WHITE
#define ENEMY_TYPE_1_TINT (Color){255, 200, 200, 255}
#define ENEMY_TYPE_2_TINT (Color){200, 200, 255, 255}

#define PLAYER_FALLBACK_COLOR BLUE

#define SPRITE_SIZE 32
#define ENEMY_TYPE_0_SPRITE_X 32
#define ENEMY_TYPE_1_SPRITE_X 64
#define ENEMY_TYPE_2_SPRITE_X 96
#define PLAYER_SPRITE_X 0
#define SPRITE_Y 0

#define UI_BACKGROUND_COLOR Fade(BLACK, UI_FADE_ALPHA)
#define UI_BORDER_COLOR WHITE

#define TURN_INDICATOR_PLAYER_COLOR GREEN
#define TURN_INDICATOR_ENEMY_COLOR RED

#endif
