#ifndef HERO_UI_CONSTANTS_H
#define HERO_UI_CONSTANTS_H

// Hero selection screen layout
#define HERO_SELECTION_TITLE_Y 50
#define HERO_SELECTION_INSTRUCTIONS_Y 100
#define HERO_SELECTION_TITLE_FONT_SIZE 32
#define HERO_SELECTION_INSTRUCTIONS_FONT_SIZE 16
#define HERO_SELECTION_TITLE_OFFSET_X 150
#define HERO_SELECTION_INSTRUCTIONS_OFFSET_X 280

// Hero panel dimensions
#define HERO_PANEL_WIDTH 200
#define HERO_PANEL_HEIGHT 300
#define HERO_PANEL_START_Y 150
#define HERO_PANEL_BORDER_OFFSET 10
#define HERO_PANEL_PADDING 10

// Hero sprite display
#define HERO_SPRITE_SOURCE_SIZE 32
#define HERO_SPRITE_DISPLAY_SIZE 64
#define HERO_SPRITE_Y_OFFSET 20

// Text positioning
#define HERO_NAME_Y_OFFSET 100
#define HERO_NAME_FONT_SIZE 20
#define HERO_STATS_Y_OFFSET 130
#define HERO_STATS_FONT_SIZE 14
#define HERO_DESCRIPTION_Y_OFFSET 230
#define HERO_DESCRIPTION_FONT_SIZE 12
#define HERO_DESCRIPTION_LINE_HEIGHT 16
#define HERO_DESCRIPTION_PADDING 30
#define HERO_DESCRIPTION_CHARS_PER_PIXEL 8
#define HERO_DESCRIPTION_LINE_BUFFER_SIZE 64

#endif
