#ifndef UI_CONSTANTS_H
#define UI_CONSTANTS_H

#define UI_PADDING 10
#define UI_TEXT_SIZE 16
#define UI_SMALL_TEXT_SIZE 14
#define UI_TINY_TEXT_SIZE 12

#define MAIN_UI_PANEL_X 10
#define MAIN_UI_PANEL_Y 10
#define MAIN_UI_PANEL_WIDTH 200
#define MAIN_UI_PANEL_HEIGHT 120

#define STATS_UI_PANEL_X 10
#define STATS_UI_PANEL_Y 140
#define STATS_UI_PANEL_WIDTH 200
#define STATS_UI_PANEL_HEIGHT 80

#define UI_LINE_HEIGHT 20
#define UI_TEXT_OFFSET_X 10
#define UI_TEXT_OFFSET_Y 10

#define HELP_TEXT_Y_OFFSET 100
#define HELP_TEXT_LINE_SPACING 20

#define MESSAGES_START_Y 250
#define MESSAGES_LINE_HEIGHT 20

#define HEALTH_BAR_WIDTH 24
#define HEALTH_BAR_HEIGHT 4
#define HEALTH_BAR_OFFSET_Y 6
#define HEALTH_BAR_OFFSET_X 2

#define UI_FADE_ALPHA 0.7f

// Game Over Screen Constants
#define GAME_OVER_OVERLAY_ALPHA 0.8f
#define GAME_OVER_TITLE_FONT_SIZE 48
#define GAME_OVER_TEXT_FONT_SIZE 20
#define GAME_OVER_TITLE_OFFSET_X 120
#define GAME_OVER_TITLE_OFFSET_Y 50
#define GAME_OVER_LEVEL_OFFSET_X 100
#define GAME_OVER_LEVEL_OFFSET_Y 0
#define GAME_OVER_RESTART_OFFSET_X 80
#define GAME_OVER_RESTART_OFFSET_Y 30

// Stats Layout Constants
#define STATS_SECOND_COLUMN_OFFSET 80

// Enemy Display Constants
#define ENEMY_CIRCLE_RADIUS_DIVISOR 3
#define ENEMY_CIRCLE_CENTER_DIVISOR 2

#endif
