#ifndef UI_CONSTANTS_H
#define UI_CONSTANTS_H

#define UI_PADDING 10
#define UI_TEXT_SIZE 16
#define UI_SMALL_TEXT_SIZE 14
#define UI_TINY_TEXT_SIZE 12

#define MAIN_UI_PANEL_X 10
#define MAIN_UI_PANEL_Y 10
#define MAIN_UI_PANEL_WIDTH 200
#define MAIN_UI_PANEL_HEIGHT 120

#define STATS_UI_PANEL_X 10
#define STATS_UI_PANEL_Y 140
#define STATS_UI_PANEL_WIDTH 200
#define STATS_UI_PANEL_HEIGHT 80

#define UI_LINE_HEIGHT 20
#define UI_TEXT_OFFSET_X 10
#define UI_TEXT_OFFSET_Y 10

#define HELP_TEXT_Y_OFFSET 100
#define HELP_TEXT_LINE_SPACING 20

#define MESSAGES_START_Y 250
#define MESSAGES_LINE_HEIGHT 20

#define HEALTH_BAR_WIDTH 24
#define HEALTH_BAR_HEIGHT 4
#define HEALTH_BAR_OFFSET_Y 6
#define HEALTH_BAR_OFFSET_X 2

#define UI_FADE_ALPHA 0.7f

#endif
